run:
  mode: train
  model_ckpt_dir: ./models/checkpoints
  model_ckpt_name: default-runid
  project: lrec-coling2024
  name: cascade-captioning
dataset:
  name: vatex
  json_dir: ./data/VATEX
  feature_dir: ./data/VATEX_CLIP4Clip
model:
  input_size: 512
  num_videos: 1
  emb_size: 512
  nhead: 8
  dim_feedforward: 512
  num_encoder_layers: 3
  num_decoder_layers: 3
  dropout: 0.5
  input_method: soft-alignment
train:
  finetune: False
  num_epoch: 500
  batch_size: 128
  adam_lr: 0.0001
